  language: objective-c
  matrix:
      include:
          - osx_image: xcode7.3
          - osx_image: xcode8
  android:
      components:
          - tools
          - platform-tools
          - tools
          - build-tools-25.0.1
          - android-25
          - extra-google-m2repository
          - extra-android-m2repository
    
  install:
      - gem install cocoapods --pre
      - brew install jq
      - npm install shelljs -g
      - npm install glob
      
  before_script:
      - rm -rf ~/Library/Developer/Xcode/DerivedData
      - npm install -g cordova
  script:
      - cordova create app
      - cd app
      - cordova platform add android
      - cordova platform add ios
      - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push.git
      - cordova build android
